In [1]:
import torch #import the library

In [2]:
# Create tensor
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
t.t() # transpose

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [4]:
# Create tensor of zeros
z = torch.zeros(3, 3)
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## Numpy Support:
You can easily create a tensors from an ndarray and vice versa. These operations are fast, since the data of both structures will share the same memory space, and so no copying is involved.

In [5]:
# Numpy to torch tensor

import numpy as np

n = np.random.randn(1, 2)
t = torch.from_numpy(n)
print(t)
print(type(n))
print(type(t))

tensor([[-0.7592,  0.8048]], dtype=torch.float64)
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [6]:
# Tensor to numpy

n1 = t.numpy()
print(n1)
print(type(n1))

[[-0.75923403  0.80484303]]
<class 'numpy.ndarray'>


## Resizing: 
If you want to resize/reshape tensor, you can use torch.view:

In [7]:
x = torch.randn(2, 2)
y = x.view(4)
z = x.view(-1, 2)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([2, 2]) torch.Size([4]) torch.Size([2, 2])


## Autograd:
torch.autograd provides classes and functions implementing automatic differentiation of arbitrary scalar valued functions. It requires minimal changes to the existing code - you only need to declare Tensors for which gradients should be computed with the requires_grad=True keyword.

In [8]:
from torch.autograd import Variable
a = Variable(torch.Tensor([[1,2],[3,4]]), requires_grad=True)
print(a)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [9]:
y = torch.sum(a**3) # 1 + 8 + 27 + 64
print(y)

tensor(100., grad_fn=<SumBackward0>)


gradient will be calculated when we will call the .backward() method and .grad.data will store the gradients 

In [10]:
y.backward()       # compute gradients of y wrt a
print(a.grad.data)      # print dy/da_ij = 3*a_ij^2 for a_11, a_12, a21, a22

tensor([[ 3., 12.],
        [27., 48.]])


## Simple Neaural Network Feedforward:

Mathematically this looks like: 

$$
\begin{align}
y &= f(w_1 x_1 + w_2 x_2 + b) \\
y &= f\left(\sum_i w_i x_i +b \right)
\end{align}
$$

With vectors this is the dot/inner product of two vectors:

$$
h = \begin{bmatrix}
x_1 \, x_2 \cdots  x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_1 \\
           w_2 \\
           \vdots \\
           w_n
\end{bmatrix}
$$

we need to do dot/inner proudct between the input data with set of weights and then add the bias.
Then we pass it through an activation function.

In [11]:
torch.manual_seed(2) # setting random seed for reproducability

In [12]:
X = torch.randn((1, 5)) # 2,5 random normal input featutres/tensor
w = torch.rand_like(X) # weights with same dimension as features
b = torch.randn(1,1) # bias unit

In [13]:
# Sigmoid activation function

def sigmoid(i):
    return 1/(1+torch.exp(-i))

In [14]:
# To check the shape of the tensor
w.shape

torch.Size([1, 5])

As you might have guessed we cannot straightaway do - dot product of X and w as the inner dimnesions do not match here.We need reshape the weight tensor to a 5,2 tensor. View function can help us to do that.

In [15]:
w.view(5,1).shape

torch.Size([5, 1])

In [16]:
y = sigmoid((torch.mm(X,w.view(5,1))+b))
y # showing output from single layer

tensor([[0.2763]])